"""Story selector for the LinkedIn post proposer (scripts/propose_linkedin_post.py).

Picks the event cluster whose coverage is broadest on BOTH sides of the
strait — the project's split-screen angle applied to one story — and
exposes every ranking factor so the analyst can see why it won.

Deterministic, no AI. Reads `articles` + `ai_analysis` + `sources` through
a plain sqlite connection; the ranking itself is pure (`rank_clusters`) so
it is unit-testable without a DB. Nothing here writes.

A cluster is a candidate when ALL of:
  - at least one member was published inside the window (default 48 h);
  - it has at least one member that has passed the human approval gate
    (analyst_approved=1 and no unresolved review flag — the public feed's
    own visibility predicate, api/routes/articles.py _PUBLIC_VISIBLE).
    Pending members do not disqualify it (Ed, 2026-09-04) but they are
    INVISIBLE to it: sides, outlets, means, topic, headline and the draft
    material are computed from approved members only, so nothing
    unvetted can be quoted; their count is exposed as pending_n;
  - its dominant topic (mode of topic_primary, ties to the earliest
    member) is not in EXCLUDED_TOPICS;
  - it carries at least one Taiwan-side outlet AND one PRC-side outlet;
  - it has not been proposed before (same cluster id, or sharing any
    article with a previously proposed cluster — cluster ids are
    regenerated by cluster_events.py every tick, so an id alone is not a
    stable identity for a story).

Ranking: cross-side breadth first (harmonic mean of distinct TW outlets
and distinct PRC outlets, so 3+3 → 3.0 beats 6+1 → 1.71), then sentiment
divergence between the two sides (|mean TW score − mean PRC score|),
then article count.

Sides: TW = place 'TW' with bias green … blue (place is required because
Zaobao and BBC Chinese are also `centrist`); PRC = bias state_official /
state_nationalist / china_centrist, which deliberately admits RTHK and
Ming Pao (HK) as Beijing-side voices. International outlets count towards
article totals but towards neither side.

"Outlet" collapses section feeds to the publication (UDN + UDN Breaking =
one outlet), mirroring the feed's PUBLICATION_NAMES in SourceBadge.jsx.
"""
from __future__ import annotations

import json
from collections import Counter

WINDOW_HOURS = 48
TOP_N = 3

TW_SIDE_BIASES = {'green', 'green_leaning', 'centrist', 'blue_leaning', 'blue'}
PRC_SIDE_BIASES = {'state_official', 'state_nationalist', 'china_centrist'}

# Domestic-Taiwan-politics topics excluded from candidate selection.
# Ed confirms/edits this list (proposer step 1). NOT_RELEVANT is a safety
# net: it should never dominate an approved cluster, but if it does the
# cluster is not a cross-strait story.
EXCLUDED_TOPICS = {'POL_DOMESTIC_TW', 'NOT_RELEVANT'}

# Section feeds → publication. Anything not listed is its own outlet.
_SECTION_PREFIXES = (
    ('LTN ', 'Liberty Times'),
    ('CNA ', 'CNA'),
    ('UDN', 'United Daily News'),
    ('CT ', 'China Times'),
    ('Ming Pao', 'Ming Pao'),
)


def outlet_of(source_name: str) -> str:
    name = (source_name or '').strip()
    for prefix, pub in _SECTION_PREFIXES:
        if name.startswith(prefix):
            return pub
    return name


def side_of(place: str | None, bias: str | None) -> str | None:
    """'TW', 'PRC' or None (international / unlabelled)."""
    if bias in PRC_SIDE_BIASES:
        return 'PRC'
    if place == 'TW' and bias in TW_SIDE_BIASES:
        return 'TW'
    return None


# ── data access ─────────────────────────────────────────────────────────────

_ROWS_SQL = """
SELECT a.id, CAST(a.event_cluster_id AS TEXT) AS cluster_id,
       a.published_at, a.url, a.language,
       COALESCE(a.title_en_override, a.title_en, a.title_original) AS title_en,
       a.analyst_approved,
       s.name AS source_name, s.place, s.bias,
       ai.topic_primary, ai.sentiment, ai.sentiment_score, ai.urgency,
       COALESCE(a.summary_en_override, ai.summary_en) AS summary_en,
       ai.key_quote,
       COALESCE(a.key_quote_override, ai.key_quote_en) AS key_quote_en,
       ai.is_new_formulation, ai.is_escalation_signal,
       COALESCE(ai.needs_human_review, 0) AS needs_human_review,
       COALESCE(ai.review_resolved, 0) AS review_resolved
FROM articles a
JOIN sources s ON s.id = a.source_id
LEFT JOIN ai_analysis ai
       ON ai.id = (SELECT MAX(id) FROM ai_analysis WHERE article_id = a.id)
WHERE a.is_hidden = 0
  AND a.event_cluster_id IS NOT NULL
  AND CAST(a.event_cluster_id AS TEXT) IN (
        SELECT DISTINCT CAST(event_cluster_id AS TEXT) FROM articles
        WHERE event_cluster_id IS NOT NULL AND is_hidden = 0
          AND published_at >= ? AND published_at < ?)
ORDER BY a.published_at
"""


def fetch_window_rows(conn, start_iso: str, end_iso: str) -> list[dict]:
    """Every non-hidden member of every cluster that has at least one
    member published in [start, end). ISO strings with the 'T' separator
    (see database.md → date-window comparisons)."""
    cur = conn.execute(_ROWS_SQL, (start_iso, end_iso))
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def fetch_proposed(conn) -> dict:
    """Identity of everything already proposed: {'cluster_ids', 'article_ids'}.
    Tolerates the linkedin_drafts table not existing yet (migration 0011)."""
    out = {'cluster_ids': set(), 'article_ids': set()}
    try:
        rows = conn.execute("SELECT cluster_id, article_ids FROM linkedin_drafts").fetchall()
    except Exception:  # sqlite3.OperationalError: no such table
        return out
    for cid, ids in rows:
        out['cluster_ids'].add(str(cid))
        try:
            out['article_ids'].update(int(i) for i in json.loads(ids or '[]'))
        except (ValueError, TypeError):
            pass
    return out


# ── pure ranking ────────────────────────────────────────────────────────────

def _is_approved(r) -> bool:
    return bool(r.get('analyst_approved')) and not (
        r.get('needs_human_review') and not r.get('review_resolved'))


def _mean(vals):
    vals = [v for v in vals if v is not None]
    return (sum(vals) / len(vals)) if vals else None


def dominant_topic(rows) -> str | None:
    """Mode of topic_primary; ties go to the earliest-published member."""
    topics = [r.get('topic_primary') for r in rows if r.get('topic_primary')]
    if not topics:
        return None
    counts = Counter(topics)
    best = max(counts.values())
    tied = {t for t, c in counts.items() if c == best}
    if len(tied) == 1:
        return tied.pop()
    for r in sorted(rows, key=lambda r: r.get('published_at') or ''):
        if r.get('topic_primary') in tied:
            return r['topic_primary']
    return None


def breadth_score(tw_outlets: int, prc_outlets: int) -> float:
    """Harmonic mean of per-side outlet counts: rewards balance, so
    3+3 (3.0) outranks 6+1 (1.71) and 4+2 (2.67)."""
    if tw_outlets <= 0 or prc_outlets <= 0:
        return 0.0
    return 2.0 * tw_outlets * prc_outlets / (tw_outlets + prc_outlets)


def describe_cluster(cluster_id: str, rows: list[dict]) -> dict:
    """Ranking factors + per-side material for one cluster. Pure."""
    members = sorted(rows, key=lambda r: r.get('published_at') or '')
    rows = [r for r in members if _is_approved(r)]
    pending = [r['id'] for r in members if not _is_approved(r)]
    sides = {'TW': [], 'PRC': [], 'INTL': []}
    for r in rows:
        r = dict(r)
        r['side'] = side_of(r.get('place'), r.get('bias')) or 'INTL'
        r['outlet'] = outlet_of(r.get('source_name'))
        sides[r['side']].append(r)

    tw_outlets = sorted({r['outlet'] for r in sides['TW']})
    prc_outlets = sorted({r['outlet'] for r in sides['PRC']})
    tw_mean = _mean(r.get('sentiment_score') for r in sides['TW'])
    prc_mean = _mean(r.get('sentiment_score') for r in sides['PRC'])
    divergence = abs(tw_mean - prc_mean) if (tw_mean is not None and prc_mean is not None) else 0.0

    return {
        'cluster_id': str(cluster_id),
        'headline': next((r.get('title_en') for r in rows if r.get('title_en')), str(cluster_id)),
        'n_articles': len(rows),              # approved members — what the post is built on
        'pending_n': len(pending),
        'n_members': len(members),
        'article_ids': [r['id'] for r in members],   # ALL members: dedup identity
        'approved_ids': [r['id'] for r in rows],
        'pending_ids': pending,
        'tw_n': len(sides['TW']),
        'prc_n': len(sides['PRC']),
        'intl_n': len(sides['INTL']),
        'tw_outlets': tw_outlets,
        'prc_outlets': prc_outlets,
        'breadth': round(breadth_score(len(tw_outlets), len(prc_outlets)), 3),
        'tw_mean': None if tw_mean is None else round(tw_mean, 3),
        'prc_mean': None if prc_mean is None else round(prc_mean, 3),
        'divergence': round(divergence, 3),
        'dominant_topic': dominant_topic(rows),
        'topics': dict(Counter(r.get('topic_primary') for r in rows if r.get('topic_primary'))),
        'oldest_published': rows[0].get('published_at') if rows else None,
        'newest_published': rows[-1].get('published_at') if rows else None,
        'sides': sides,
    }


def exclusion_reasons(c: dict, proposed: dict | None = None,
                      excluded_topics=None) -> list[str]:
    excluded_topics = EXCLUDED_TOPICS if excluded_topics is None else excluded_topics
    proposed = proposed or {'cluster_ids': set(), 'article_ids': set()}
    reasons = []
    if not c['approved_ids']:
        reasons.append('no_approved_members')
    if c['dominant_topic'] in excluded_topics:
        reasons.append(f"excluded_topic:{c['dominant_topic']}")
    if not c['tw_outlets']:
        reasons.append('no_tw_side')
    if not c['prc_outlets']:
        reasons.append('no_prc_side')
    if c['cluster_id'] in proposed['cluster_ids']:
        reasons.append('already_proposed:cluster')
    elif proposed['article_ids'].intersection(c['article_ids']):
        reasons.append('already_proposed:shares_articles')
    return reasons


def rank_key(c: dict):
    return (-c['breadth'], -c['divergence'], -c['n_articles'], c['cluster_id'])


def rank_clusters(rows: list[dict], proposed: dict | None = None, top_n: int = TOP_N,
                  excluded_topics=None) -> tuple[list[dict], list[dict]]:
    """(candidates ranked best-first, top_n of them; excluded clusters with
    reasons). Input is the flat row list from fetch_window_rows."""
    by_cluster: dict[str, list] = {}
    for r in rows:
        by_cluster.setdefault(str(r['cluster_id']), []).append(r)

    ranked, excluded = [], []
    for cid, crows in by_cluster.items():
        c = describe_cluster(cid, crows)
        reasons = exclusion_reasons(c, proposed, excluded_topics)
        if reasons:
            c['excluded_because'] = reasons
            excluded.append(c)
        else:
            ranked.append(c)
    ranked.sort(key=rank_key)
    excluded.sort(key=rank_key)
    for i, c in enumerate(ranked, 1):
        c['rank'] = i
    return ranked[:top_n], excluded


def select_candidates(conn, start_iso: str, end_iso: str, proposed: dict | None = None,
                      top_n: int = TOP_N):
    """DB-backed convenience: rows → ranked top_n + exclusions."""
    return rank_clusters(fetch_window_rows(conn, start_iso, end_iso), proposed, top_n)
